server:
  port: ${SERVER_PORT:9090}
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic-name:
      changes-data: ${KAFKA_TOPIC_NAME:changes-data-set}
    groups:
      events-data-group-id: ${KAFKA_EVENTS_DATA_GROUP_ID:elastic}
  elasticsearch:
    host:  ${ELASTIC_HOST:localhost}
    port: ${ELASTIC_PORT:9200}
    connection-timeout: 5000
    socket-timeout: 12000
    scheme: http
    cert-path: ${ELASTIC_CERT_PATH:src/main/resources/certificates/CA.jks}
    cert-password: ${ELASTIC_CERT_PATH:123456}
    topics-names: ${KAFKA_PRODUCER_TOPIC_NAME:history}
    password: admin
    username: admin
